=== sakamoto-poteko/Monicelli/dtd/geometry.dtd
<?xml encoding="ISO-8859-1"?>

<!-- Author  : D. Menasce, S. Terzo -->
<!-- @version: 1.0                  -->

<!ELEMENT testBeamGeometry                         (stations                 )                   >
<!ATTLIST testBeamGeometry                          run                          CDATA #REQUIRED  
                                                    description                  CDATA #IMPLIED
                                                    date                         CDATA #IMPLIED  >
  <!ELEMENT stations                               (station+                 )                   >
  <!ATTLIST stations                                inUse                        CDATA #REQUIRED >
    <!ELEMENT station                              (detectors                )                   >
    <!ATTLIST station                               id                           CDATA #REQUIRED 
                                                    serial                       CDATA #IMPLIED
                                                    used                         CDATA #REQUIRED 
                                                    description                  CDATA #IMPLIED  >               
      <!ELEMENT detectors                          (detector+                )                   >
      <!ATTLIST detectors                           inUse                        CDATA #REQUIRED >
        <!ELEMENT detector                         (largeGranularity,         
                                                    fineGranularity?,         
                                                    ROCs                     )                   >     
        <!ATTLIST detector                          id                           CDATA #REQUIRED
                                                    serial                       CDATA #IMPLIED
                                                    name                         CDATA #IMPLIED
						    isDUT                        CDATA #IMPLIED
                                                    used                         CDATA #REQUIRED 
                                                    description                  CDATA #IMPLIED  >                   
          <!ELEMENT largeGranularity               (xBackFlipped,             
                                                    yBackFlipped, 
                                                    xPosition   ,
                                                    yPosition   ,            
                                                    zPosition   ,
                                                    xRotation   ,
                                                    yRotation   ,
                                                    zRotation                )                   >
          <!ATTLIST largeGranularity                relativeRotations            CDATA #REQUIRED >
            <!ELEMENT xBackFlipped                 (#PCDATA                  )*                  >
            <!ELEMENT yBackFlipped                 (#PCDATA                  )*                  >
            <!ELEMENT xPosition                    (#PCDATA                  )*                  >
            <!ELEMENT yPosition                    (#PCDATA                  )*                  >
            <!ELEMENT zPosition                    (#PCDATA                  )*                  >
            <!ELEMENT xRotation                    (#PCDATA                  )*                  >
            <!ELEMENT yRotation                    (#PCDATA                  )*                  >
            <!ELEMENT zRotation                    (#PCDATA                  )*                  >
          <!ELEMENT fineGranularity                (xPosCorrection          ,
                                                    xPositionError          ,
                                                    yPosCorrection          ,
                                                    yPositionError          ,
                                                    zPosCorrection          ,
                                                    zPositionError          ,
                                                    xRotationCorrection     ,
                                                    xRotationCorrectionError,
                                                    yRotationCorrection     ,
                                                    yRotationCorrectionError,
                                                    zRotationCorrection     ,
                                                    zRotationCorrectionError )                   >
          <!ATTLIST fineGranularity                 relativeRotations            CDATA #REQUIRED >
            <!ELEMENT xPosCorrection               (#PCDATA                  )*                  >
            <!ELEMENT xPositionError               (#PCDATA                  )*                  >
            <!ELEMENT yPosCorrection               (#PCDATA                  )*                  >
            <!ELEMENT yPositionError               (#PCDATA                  )*                  >
            <!ELEMENT zPosCorrection               (#PCDATA                  )*                  >
            <!ELEMENT zPositionError               (#PCDATA                  )*                  >               
            <!ELEMENT xRotationCorrection          (#PCDATA                  )*                  >                        
            <!ELEMENT xRotationCorrectionError     (#PCDATA                  )*                  >                        
            <!ELEMENT yRotationCorrection          (#PCDATA                  )*                  >                        
            <!ELEMENT yRotationCorrectionError     (#PCDATA                  )*                  >                        
            <!ELEMENT zRotationCorrection          (#PCDATA                  )*                  >                        
            <!ELEMENT zRotationCorrectionError     (#PCDATA                  )*                  >   
          <!ELEMENT ROCs                           (ROC+                     )                   >
          <!ATTLIST ROCs                            inUse                        CDATA #IMPLIED 
                                                    xChipsNumber                 CDATA #REQUIRED
                                                    yChipsNumber                 CDATA #REQUIRED >
            <!ELEMENT ROC                          (calibrationFilePath ,
	                                            standardRowPitch    ,
                                                    standardColPitch    ,    
                                                    nonStandardRowPitch*,
                                                    nonStandardColPitch*,
                                                    MAX_ROWS            ,   
                                                    MAX_COLS            ,   
                                                    orientation              )                   >                                        
            <!ATTLIST ROC                           id                           CDATA #REQUIRED
                                                    serial                       CDATA #IMPLIED
                                                    pos                          CDATA #REQUIRED
                                                    used                         CDATA #REQUIRED 
                                                    description                  CDATA #IMPLIED  >  
	      <!ELEMENT calibrationFilePath        (#PCDATA                  )*                  >
              <!ELEMENT standardRowPitch           (#PCDATA                  )*                  >
              <!ELEMENT standardColPitch           (#PCDATA                  )*                  > 
              <!ELEMENT nonStandardRowPitch        (#PCDATA                  )*                  >
              <!ATTLIST nonStandardRowPitch         rowNum                       CDATA #REQUIRED >
              <!ELEMENT nonStandardColPitch        (#PCDATA                  )*                  > 
              <!ATTLIST nonStandardColPitch         colNum                       CDATA #REQUIRED >                                                                       
              <!ELEMENT MAX_ROWS                   (#PCDATA                  )*                  >
              <!ELEMENT MAX_COLS                   (#PCDATA                  )*                  >                                        
              <!ELEMENT orientation                (#PCDATA                  )*                  >

=== sakamoto-poteko/Monicelli/xml/geometry2011last.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE testBeamGeometry SYSTEM '../dtd/geometry.dtd'>
<!--   Author  : D. Menasce, S. Terzo   -->
<!--   @version: 1.0                    -->
<testBeamGeometry run="23" date="11/12/2010">
  <stations inUse="3">
    <station serial="0" description="" id="0" used="yes">
      <detectors inUse="4">
        <detector serial="0" description="" id="0" name="CMS FPIX" used="yes">
          <largeGranularity relativeRotations="beam">
            <xBackFlipped>  yes </xBackFlipped>
            <yBackFlipped>  yes</yBackFlipped>
            <xPosition>     0   </xPosition>
            <yPosition>     0   </yPosition>
            <zPosition>     43   </zPosition>
            <xRotation>    -26  </xRotation>
            <yRotation>     0   </yRotation>
            <zRotation>     0   </zRotation>
          </largeGranularity>
          <fineGranularity relativeRotations="beam">
            <xPosCorrection>       0  </xPosCorrection>
            <xPositionError>            0  </xPositionError>
            <yPosCorrection>       0  </yPosCorrection>
            <yPositionError>            0  </yPositionError>
            <zPosCorrection>       0  </zPosCorrection>
            <zPositionError>            0  </zPositionError>
            <xRotationCorrection>  -0.78534  </xRotationCorrection>
            <xRotationCorrectionError>  0  </xRotationCorrectionError>
            <yRotationCorrection>  0.73916  </yRotationCorrection>
            <yRotationCorrectionError>  0  </yRotationCorrectionError>
            <zRotationCorrection>  -1.06476  </zRotationCorrection>
            <zRotationCorrectionError>  0  </zRotationCorrectionError>
          </fineGranularity>
          <ROCs yChipsNumber="2" xChipsNumber="4" inUse="8">
            <ROC serial="0" id="0" pos="0" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_0_0.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
              <orientation>   0    </orientation>
            </ROC>
            <ROC serial="1" id="1" pos="1" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_0_1.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
              <orientation>   0    </orientation>
            </ROC>
            <ROC serial="2" id="2" pos="2" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_0_2.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
              <orientation>   0    </orientation>
            </ROC>
            <ROC serial="3" id="3" pos="3" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_0_3.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
              <orientation>   0    </orientation>
            </ROC>
            <ROC serial="4" id="4" pos="4" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_0_4.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
              <orientation>  180   </orientation>
            </ROC>
            <ROC serial="5" id="5" pos="5" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_0_5.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
              <orientation>  180   </orientation>
            </ROC>
            <ROC serial="6" id="6" pos="6" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_0_6.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
              <orientation>  180   </orientation>
            </ROC>
            <ROC serial="7" id="7" pos="7" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_0_7.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
              <orientation>  180   </orientation>
            </ROC>
          </ROCs>
        </detector>
        <detector serial="1" description="" id="1" name="CMS FPIX" used="yes">
          <largeGranularity relativeRotations="beam">
            <xBackFlipped>no</xBackFlipped>
            <yBackFlipped>  yes  </yBackFlipped>
            <xPosition>     0    </xPosition>
            <yPosition>     0    </yPosition>
            <zPosition>     41    </zPosition>
            <xRotation>    -26   </xRotation>
            <yRotation>     0    </yRotation>
            <zRotation>     0    </zRotation>
          </largeGranularity>
          <fineGranularity relativeRotations="beam">
            <xPosCorrection>       0  </xPosCorrection>
            <xPositionError>            0  </xPositionError>
            <yPosCorrection>       0  </yPosCorrection>
            <yPositionError>            0  </yPositionError>
            <zPosCorrection>       0  </zPosCorrection>
            <zPositionError>            0  </zPositionError>
            <xRotationCorrection> -0.75292  </xRotationCorrection>
            <xRotationCorrectionError>  0  </xRotationCorrectionError>
            <yRotationCorrection>  1.15267  </yRotationCorrection>
            <yRotationCorrectionError>  0  </yRotationCorrectionError>
            <zRotationCorrection>  -0.889418  </zRotationCorrection>
            <zRotationCorrectionError>  0  </zRotationCorrectionError>
          </fineGranularity>
          <ROCs yChipsNumber="2" xChipsNumber="4" inUse="8">
            <ROC serial="0" id="0" pos="0" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_10_0.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
              <orientation>   0    </orientation>
            </ROC>
            <ROC serial="1" id="1" pos="1" used="yes">
              <calibrationFilePath>    TELESCOPE_CAL_3_24_2011_0_10_1.txt   </calibrationFilePath>
              <standardRowPitch>   0.010   </standardRowPitch>
              <standardColPitch>   0.015   </standardColPitch>
              <nonStandardRowPitch rowNum="79">   0.02  </nonStandardRowPitch>
              <nonStandardColPitch colNum="0">    0.03  </nonStandardColPitch>
              <nonStandardColPitch colNum="51">   0.03  </nonStandardColPitch>
              <MAX_ROWS>     79    </MAX_ROWS>
              <MAX_COLS>     51    </MAX_COLS>
